/* Gestão de cuidadores e vínculos por turno — nível 1. */
(function(){
'use strict';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={users:[],patients:[],links:[],selected:null,dirty:false,busy:false};
const allowed=()=>Number(localStorage.getItem('usuario_hierarquia'))===1;
const turns=[['manha','Manhã'],['tarde','Tarde'],['noite','Noite']];
function status(text,error=false){$('eqMessage').textContent=text;$('eqMessage').dataset.error=String(error);}
function linked(id){return state.links.filter(v=>v.usuario_id===id);}
function setup(){const panel=$('painelEquipe');if(!panel||panel.dataset.ready)return;panel.dataset.ready='1';panel.innerHTML=`<div class="nt-heading"><div><span class="nt-kicker">Harmonia Care · gestão da equipe</span><h2>Cuidadores e pacientes</h2><p class="nt-muted">Veja a distribuição dos pacientes e edite os vínculos por turno.</p></div><div class="nt-actions"><button id="eqRefresh">Atualizar</button><button id="eqPDF" class="nt-primary">Relatório de vínculos</button></div></div>
<form id="eqAuth" class="nt-card" hidden><h3>Confirmar acesso de nível 1</h3><p>Entre com sua conta do Harmonia Care para gerenciar os vínculos.</p><div class="nt-grid"><label>Usuário<input id="eqLogin" autocomplete="username" required></label><label>Senha<input id="eqPassword" type="password" autocomplete="current-password" required></label><button class="nt-primary" id="eqAuthSubmit">Confirmar acesso</button></div></form><div id="eqMessage" class="nt-message" role="status" aria-live="polite"></div><div class="nt-kpis" id="eqKpis"></div>
<div class="nt-filters"><label>Buscar cuidador ou paciente<input id="eqSearch" placeholder="Digite um nome…"></label><label>Situação<select id="eqStatus"><option value="ativos">Cuidadores ativos</option><option value="todos">Todos</option><option value="inativos">Inativos</option></select></label><label>Vínculos<select id="eqFilter"><option value="todos">Todos</option><option value="sem">Sem pacientes vinculados</option><option value="com">Com pacientes vinculados</option></select></label></div>
<div class="eq-layout"><div class="nt-card"><h3>Equipe e distribuição</h3><div id="eqList"></div></div><form id="eqEditor" class="nt-card" hidden><div class="nt-heading"><h3 id="eqEditorTitle">Editar cuidador</h3><button type="button" id="eqCancel">Fechar</button></div><div class="nt-grid">${[['nome','Nome completo','text'],['apelido','Usuário / apelido','text'],['email','E-mail','email'],['telefone','Telefone','tel']].map(([id,label,type])=>`<label class="nt-span">${label}<input id="eq_${id}" type="${type}" ${id!=='telefone'?'required':''} maxlength="180"></label>`).join('')}<label>Situação<select id="eq_ativo"><option value="true">Ativo</option><option value="false">Inativo</option></select></label></div><h3 style="margin-top:24px">Pacientes por turno</h3><p class="nt-muted">Marque os turnos em que o cuidador terá o paciente vinculado. Desmarcar remove apenas o vínculo, preservando os registros assistenciais.</p><label>Localizar paciente<input id="eqPatientSearch" placeholder="Buscar na lista…"></label><div class="nt-actions" style="margin:12px 0">${turns.map(([value,label])=>`<button type="button" data-eq-turn="${value}">Marcar ${label}</button>`).join('')}<button type="button" id="eqClear" class="nt-danger">Desmarcar visíveis</button></div><div class="nt-table eq-patients"><table><thead><tr><th>Paciente</th><th>Manhã</th><th>Tarde</th><th>Noite</th></tr></thead><tbody id="eqPatients"></tbody></table></div><div class="nt-actions eq-save"><button id="eqSave" type="submit" class="nt-primary">Salvar cadastro e vínculos</button><span id="eqDraft" class="nt-muted"></span></div></form></div><div class="nt-card"><h3>Pacientes ativos sem cuidador vinculado</h3><div id="eqUnassigned" class="nt-muted"></div></div>`;
$('eqRefresh').onclick=async()=>{if(!discard())return;await load();};$('eqSearch').oninput=renderList;$('eqStatus').onchange=renderList;$('eqFilter').onchange=renderList;$('eqPDF').onclick=pdf;$('eqCancel').onclick=discard;$('eqEditor').onsubmit=save;$('eqPatientSearch').oninput=filterPatients;
$('eqEditor').addEventListener('input',e=>{if(e.target.id==='eqPatientSearch')return;state.dirty=true;draft();});$('eqEditor').addEventListener('change',()=>{state.dirty=true;draft();});
$('eqAuth').onsubmit=async e=>{e.preventDefault();$('eqAuthSubmit').disabled=true;try{await window.HarmoniaNutricao.authenticate($('eqLogin').value,$('eqPassword').value);$('eqPassword').value='';$('eqAuth').hidden=true;await load();}catch(err){status(err.message,true);}finally{$('eqAuthSubmit').disabled=false;}};
$('eqList').onclick=e=>{const b=e.target.closest('[data-eq-user]');if(b)edit(b.dataset.eqUser);};panel.querySelectorAll('[data-eq-turn]').forEach(b=>b.onclick=()=>bulk(b.dataset.eqTurn,true));$('eqClear').onclick=()=>bulk(null,false);
window.addEventListener('beforeunload',e=>{if(state.dirty){e.preventDefault();e.returnValue='';}});
}
async function load(){setup();if(!allowed()){status('Gestão disponível para usuários de nível 1.',true);return;}status('Carregando equipe e vínculos…');$('eqPDF').disabled=true;try{const data=await window.HarmoniaNutricao.api('team_list');state.users=data.users;state.patients=data.patients;state.links=data.links;$('eqAuth').hidden=true;render();status('Dados atualizados. Selecione um cuidador para editar.');$('eqPDF').disabled=false;}catch(e){status(e.message,true);if((e.message||'').includes('NUTRI_AUTH')){$('eqAuth').hidden=false;$('eqLogin').value=localStorage.getItem('usuario_nome')||'';}}}
function render(){const active=state.users.filter(u=>u.ativo);const ids=new Set(active.map(u=>u.id));const coverage=new Set(state.links.filter(v=>ids.has(v.usuario_id)).map(v=>v.paciente_id));const patients=state.patients.filter(p=>p.ativo!==false);const no=patients.filter(p=>!coverage.has(p.id));const cards=[['Cuidadores ativos',active.length],['Pacientes com cuidador',patients.filter(p=>coverage.has(p.id)).length],['Sem cuidador ativo',no.length],['Vínculos por turno',state.links.filter(v=>ids.has(v.usuario_id)).length]];$('eqKpis').innerHTML=cards.map(([l,v])=>`<div class="nt-kpi"><span>${l}</span><strong>${v}</strong></div>`).join('');$('eqUnassigned').textContent=no.length?no.map(p=>p.nome_completo).join(' · '):'Todos os pacientes ativos possuem ao menos um cuidador ativo vinculado.';renderList();}
function renderList(){const search=$('eqSearch').value.toLocaleLowerCase('pt-BR').trim(),filter=$('eqFilter').value,active=$('eqStatus').value;const list=state.users.filter(u=>{const links=linked(u.id);const names=links.map(v=>state.patients.find(p=>p.id===v.paciente_id)?.nome_completo||'').join(' ');return(active==='todos'||(active==='ativos'?u.ativo:!u.ativo))&&(filter==='todos'||(filter==='sem'?links.length===0:links.length>0))&&(!search||`${u.nome_completo} ${u.nome_apelido} ${names}`.toLocaleLowerCase('pt-BR').includes(search));});$('eqList').innerHTML=list.map(u=>{const links=linked(u.id),ids=[...new Set(links.map(v=>v.paciente_id))];return `<article class="eq-person ${state.selected?.id===u.id?'eq-selected':''}"><div class="nt-heading"><div><b>${esc(u.nome_completo)}</b><div class="nt-muted">${esc(u.nome_apelido)} · ${u.ativo?'Ativo':'Inativo'}</div></div><button data-eq-user="${u.id}" type="button">Editar / vincular</button></div><p><span class="nt-badge">${ids.length} paciente(s)</span> <span class="nt-muted">${links.length} vínculo(s) por turno</span></p><div class="eq-linked">${ids.length?ids.map(id=>`<div><span>${esc(state.patients.find(p=>p.id===id)?.nome_completo||'Paciente')}</span><small>${turns.filter(([t])=>links.some(v=>v.paciente_id===id&&v.turno===t)).map(x=>x[1]).join(' · ')}</small></div>`).join(''):'<span class="nt-muted">Sem pacientes vinculados.</span>'}</div></article>`;}).join('')||'<div class="nt-empty">Nenhum cuidador encontrado.</div>';}
function discard(){if(state.busy)return false;if(state.dirty&&!confirm('Descartar as alterações não salvas do cuidador?'))return false;state.dirty=false;state.selected=null;$('eqEditor').hidden=true;return true;}
function edit(id){if(!discard())return;const u=state.users.find(u=>u.id===id);if(!u)return;state.selected=u;$('eqEditor').hidden=false;$('eqEditorTitle').textContent='Editar · '+u.nome_completo;[['nome','nome_completo'],['apelido','nome_apelido'],['email','email'],['telefone','telefone']].forEach(([id,key])=>$('eq_'+id).value=u[key]||'');$('eq_ativo').value=String(u.ativo);$('eqPatientSearch').value='';const links=linked(id);$('eqPatients').innerHTML=state.patients.map(p=>`<tr data-patient-name="${esc(p.nome_completo.toLocaleLowerCase('pt-BR'))}"><td>${esc(p.nome_completo)}${p.ativo===false?' <small>(inativo)</small>':''}</td>${turns.map(([t,label])=>`<td><input type="checkbox" data-patient="${p.id}" data-turn="${t}" aria-label="${esc(p.nome_completo)} — ${label}" ${links.some(v=>v.paciente_id===p.id&&v.turno===t)?'checked':''}></td>`).join('')}</tr>`).join('');draft();renderList();$('eqEditor').scrollIntoView({behavior:'smooth',block:'start'});}
function filterPatients(){const text=$('eqPatientSearch').value.toLocaleLowerCase('pt-BR');$('eqPatients').querySelectorAll('tr').forEach(tr=>tr.hidden=!tr.dataset.patientName.includes(text));}
function bulk(turn,checked){$('eqPatients').querySelectorAll('tr').forEach(tr=>{if(tr.hidden)return;tr.querySelectorAll('input').forEach(el=>{if(!turn||el.dataset.turn===turn)el.checked=checked;});});state.dirty=true;draft();}
function draft(){const checked=[...$('eqPatients').querySelectorAll('input:checked')];$('eqDraft').textContent=`${new Set(checked.map(el=>el.dataset.patient)).size} paciente(s) · ${checked.length} turno(s)${state.dirty?' · Alterações não salvas':''}`;}
async function save(e){e.preventDefault();if(state.busy||!state.selected||!$('eqEditor').reportValidity())return;const u=state.selected;const links=[...$('eqPatients').querySelectorAll('input:checked')].map(el=>({paciente_id:el.dataset.patient,turno:el.dataset.turn}));const removed=linked(u.id).filter(v=>!links.some(x=>x.paciente_id===v.paciente_id&&x.turno===v.turno)).length;if(removed&&!confirm(`Salvar e remover ${removed} vínculo(s) por turno deste cuidador?`))return;
state.busy=true;$('eqSave').disabled=true;try{await window.HarmoniaNutricao.api('team_save',{id:u.id,signature:u.signature,nome_completo:$('eq_nome').value.trim(),nome_apelido:$('eq_apelido').value.trim(),email:$('eq_email').value.trim(),telefone:$('eq_telefone').value.trim(),ativo:$('eq_ativo').value==='true',links});state.dirty=false;state.selected=null;$('eqEditor').hidden=true;await load();status('Cadastro e vínculos salvos. A distribuição da equipe foi atualizada.');}catch(err){status('Não foi possível salvar: '+err.message,true);}finally{state.busy=false;$('eqSave').disabled=false;}}
function pdf(){try{if(!window.jspdf?.jsPDF)throw new Error('Recarregue a página para carregar o gerador PDF.');const doc=new window.jspdf.jsPDF();doc.setFontSize(17);doc.setTextColor(8,127,120);doc.text('Harmonia Care | Cuidadores e pacientes',14,20);doc.setFontSize(9);doc.setTextColor(70);doc.text('Distribuição completa por turno · '+new Date().toLocaleString('pt-BR'),14,28);const body=[];state.users.forEach(u=>{const links=linked(u.id);const ids=[...new Set(links.map(v=>v.paciente_id))];if(!ids.length)body.push([u.nome_completo,u.ativo?'Ativo':'Inativo','Sem vínculo','—']);ids.forEach(id=>body.push([u.nome_completo,u.ativo?'Ativo':'Inativo',state.patients.find(p=>p.id===id)?.nome_completo||'Paciente',turns.filter(([t])=>links.some(v=>v.paciente_id===id&&v.turno===t)).map(x=>x[1]).join(', ')]));});doc.autoTable({startY:35,head:[['Cuidador','Situação','Paciente','Turnos']],body,headStyles:{fillColor:[8,127,120]},styles:{fontSize:9,cellPadding:3},margin:{bottom:20}});for(let i=1;i<=doc.getNumberOfPages();i++){doc.setPage(i);doc.setFontSize(8);doc.text(`Uso interno assistencial · Página ${i}/${doc.getNumberOfPages()}`,14,286);}doc.save('harmonia-cuidadores-vinculos.pdf');}catch(e){status(e.message,true);}}
window.HarmoniaEquipe={open:load,allowed,hasUnsaved:()=>state.dirty,discard};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup,{once:true});else setup();
})();
