/* Harmonia Care — medication workspace. Prescriptions are never grouped for administration. */
(function(){
'use strict';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/\s+/g,' ').trim();
const compare=(a,b)=>String(a??'').localeCompare(String(b??''),'pt-BR',{sensitivity:'base',numeric:true});
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const date=v=>v?String(v).slice(0,10).split('-').reverse().join('/'):'Não informado';
const stamp=v=>v?new Date(v).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}):'Registro anterior';
const duration=m=>m.duracao_tipo==='temporario'?'Temporário':'Contínuo';
const controlNames={B1:'Controlado · B1',C1:'Controle especial · C1',fora_344:'Fora da Portaria 344',revisar:'Conferir identificação'};
const state={patients:[],meds:[],catalog:[],execs:[],history:[],tab:'daily',day:today(),gestor:false,page:1,historyPage:1,root:'painelMedicacao',filters:{patient:'',search:'',control:'',duration:'',group:'',status:'vigentes'},from:today(),to:today(),loaded:false,loading:null,dirty:false,historyLoaded:false};
let dialog=null,lastFocus=null,refreshTimer=null;
const tokenKey=()=>`med_token_${localStorage.getItem('usuario_id')}`;
const token=()=>sessionStorage.getItem(tokenKey());
const allowed=()=>Number(localStorage.getItem('usuario_hierarquia'))===1||['administrador','enfermeiro','medico'].includes(localStorage.getItem('usuario_perfil'));
const info=m=>m.classificacao_info||{lista:'revisar'};
const control=m=>info(m).lista||'revisar';
function status(m,d=state.day){if(m.status_tratamento==='finalizado'||m.ativo===false)return 'encerrados';if(m.status_tratamento==='suspenso')return 'suspensos';if(m.data_fim&&m.data_fim<d)return 'encerrados';if(m.data_inicio&&m.data_inicio>d)return 'futuros';return 'vigentes';}
const active=(m,d)=>status(m,d)==='vigentes'&&m.paciente_ativo!==false;
const hours=m=>[...new Set(String(m.horarios||'').split('|').filter(h=>/^([01]\d|2[0-3]):[0-5]\d$/.test(h)))].sort();
const patientName=m=>m.nome_paciente||state.patients.find(p=>p.id===m.paciente_id)?.nome_completo||'Paciente';
const orderMeds=(a,b)=>compare(patientName(a),patientName(b))||compare(a.nome_medicamento,b.nome_medicamento)||compare(a.id,b.id);
function matches(m){const f=state.filters;return (!f.patient||m.paciente_id===f.patient)&&(!f.search||norm([patientName(m),m.nome_medicamento,info(m).principio_ativo].join(' ')).includes(norm(f.search)))&&(!f.control||(f.control==='controlados'?['B1','C1'].includes(control(m)):control(m)===f.control))&&(!f.duration||m.duracao_tipo===f.duration)&&(!f.group||info(m).classe_terapeutica===f.group);}
function filtered(){return state.meds.filter(m=>matches(m)&&(state.tab==='daily'||state.tab==='hours'?active(m,state.day):(!state.filters.status||status(m)===state.filters.status))).sort(orderMeds);}
const eventFor=(m,h)=>state.execs.find(e=>e.medicacao_id===m.id&&e.horario===h&&e.data===state.day);
async function api(action,payload={}){const {data,error}=await window.db.rpc('medicacao_api',{p_action:action,p_token:token()||null,p_payload:payload});if(error){if(String(error.message).includes('MED_AUTH')){sessionStorage.removeItem(tokenKey());state.loaded=false;}throw new Error(error.message||'Não foi possível acessar o banco de dados.');}if(data?.error)throw new Error(data.error);return data;}
async function authenticate(login,senha){const data=await api('login',{login,senha});if(data.usuario_id!==localStorage.getItem('usuario_id'))throw new Error('Use a mesma conta com a qual entrou no Harmonia Care.');sessionStorage.setItem(tokenKey(),data.token);return data;}
async function executions(from,to,patient=''){let all=[];for(let offset=0;;offset+=500){const page=await api('executions',{from,to,paciente_id:patient||null,offset});all.push(...page);if(page.length<500)return all;}}
function notice(message,error=false){const el=$('hm-message');if(el){el.textContent=message;el.className='hm-message'+(error?' hm-error':'');el.hidden=false;}else alert(message);}
function authBox(){const root=$(state.root);root.classList.add('hm');root.innerHTML=`<div class="hm-auth"><div class="hm-eyebrow">HARMONIA CARE · MEDICAÇÃO</div><h2>Confirme seu acesso</h2><p>Entre com sua conta para consultar prescrições e registrar a administração.</p><form id="hm-auth-form"><label>Usuário<input name="login" autocomplete="username" required></label><label>Senha<input name="senha" type="password" autocomplete="current-password" required></label><p id="hm-auth-error" role="alert"></p><button class="hm-primary">Acessar Medicação</button></form></div>`;
 $('hm-auth-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,btn=form.querySelector('button');btn.disabled=true;try{await authenticate(form.elements.login.value,form.elements.senha.value);form.elements.senha.value='';await load();}catch(err){$('hm-auth-error')&&($('hm-auth-error').textContent=err.message);}finally{btn.disabled=false;}});}
async function load(){if(state.loading)return state.loading;state.loading=(async()=>{try{const data=await api('workspace');if(data.usuario_id!==localStorage.getItem('usuario_id'))throw new Error('A conta mudou. Entre novamente.');const events=await executions(data.hoje,data.hoje);state.day=data.hoje;state.patients=data.patients;state.meds=data.prescriptions;state.catalog=data.catalog;state.gestor=data.gestor;state.execs=events;state.loaded=true;render();}catch(e){if(!token())authBox();else notice(e.message,true);}finally{state.loading=null;}})();return state.loading;}
async function open(hoursView=false){if(!allowed()){alert('Este perfil não tem acesso à Medicação.');return;}if(dialog&&!closeDialog())return;state.root=hoursView?'painelMedicacaoHora':'painelMedicacao';$(hoursView?'painelMedicacao':'painelMedicacaoHora')?.replaceChildren();state.tab=hoursView?'hours':(state.tab==='hours'?'daily':state.tab);const root=$(state.root);root.classList.add('hm');if(!token()){authBox();return;}if(!state.loaded)root.innerHTML='<div class="hm-empty" role="status">Carregando prescrições e registros…</div>';await load();}
function options(items,value){return items.map(([v,label])=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(label)}</option>`).join('');}
function field(label,content){return `<label>${label}${content}</label>`;}
function queue(){try{return JSON.parse(localStorage.getItem('fila_medicacao')||'[]');}catch(e){return [];}}
function shell(){const f=state.filters;return `<header class="hm-heading"><div><div class="hm-eyebrow">HARMONIA CARE · ASSISTÊNCIA</div><h2>Medicação</h2><p>Prescrições, administração e histórico do paciente.</p></div><div class="hm-actions"><span class="hm-date">${date(state.day)}</span><button data-action="refresh">Atualizar</button>${state.gestor?'<button data-action="backup">Backup anterior</button><button class="hm-primary" data-action="new">+ Nova prescrição</button>':''}</div></header>
 <nav class="hm-tabs" aria-label="Visualização da medicação">${[['daily','Administração do dia'],['search','Pesquisar tratamentos'],['history','Histórico e relatórios']].map(([id,label])=>`<button data-tab="${id}" aria-current="${state.tab===id?'page':'false'}" class="${state.tab===id?'selected':''}">${label}</button>`).join('')}${state.tab==='hours'?'<button class="selected" aria-current="page">Por horário</button>':''}</nav>
 <div id="hm-message" class="hm-message" role="status" hidden></div><div id="hm-stats" class="hm-stats"></div>
 <div class="hm-filters">${field('Paciente',`<select id="hm-patient">${options([['','Todos os pacientes'],...state.patients.map(p=>[p.id,p.nome_completo+(p.ativo===false?' · inativo':'')])],f.patient)}</select>`)}${field('Medicamento ou princípio ativo',`<input id="hm-search" type="search" placeholder="Ex.: quetiapina, trazodona…" value="${esc(f.search)}">`)}${field('Controle regulatório',`<select id="hm-control">${options([['','Todos'],['controlados','Todos os controlados'],['B1','Controlados · B1'],['C1','Controle especial · C1'],['fora_344','Fora da Portaria 344'],['revisar','Conferir identificação']],f.control)}</select>`)}${field('Duração',`<select id="hm-duration">${options([['','Todas'],['continuo','Uso contínuo'],['temporario','Uso temporário']],f.duration)}</select>`)}${field('Classe terapêutica',`<select id="hm-group">${options([['','Todas as classes'],...[...new Set(state.meds.map(m=>info(m).classe_terapeutica).filter(Boolean))].sort(compare).map(c=>[c,c])],f.group)}</select>`)}${state.tab==='search'?field('Situação',`<select id="hm-status">${options([['','Todas, incluindo encerradas'],['vigentes','Vigentes'],['futuros','Início futuro'],['suspensos','Suspensas'],['encerrados','Encerradas']],f.status)}</select>`):''}<button data-action="clear">Limpar filtros</button></div>
 <div class="hm-filter-note">B1 e C1 estão incluídos no filtro “Todos os controlados”. A duração é definida na prescrição.</div>
 ${queue().length?`<div class="hm-message hm-warning">Há ${queue().length} registro(s) antigo(s) pendente(s) neste dispositivo. <button data-action="queue">Exportar para conferência</button></div>`:''}
 ${state.tab==='history'?`<div class="hm-period">${field('De',`<input type="date" id="hm-from" value="${state.from}">`)}${field('Até',`<input type="date" id="hm-to" value="${state.to}">`)}<button data-action="history" class="hm-primary">Consultar histórico</button><button data-action="pdf">Gerar PDF</button><button data-action="csv">Exportar CSV</button><span>Inclui tratamentos encerrados e registros antigos.</span></div>`:'<div class="hm-table-heading"><span id="hm-results"></span><button data-action="pdf">Relatório PDF desta seleção</button></div>'}
 <div id="hm-content"></div><footer class="hm-footer">Classificação consultada em 16/09/2026 · <a href="https://www.gov.br/anvisa/pt-br/assuntos/medicamentos/controlados/lista-substancias" target="_blank" rel="noopener">Anvisa · listas de controle</a> · <a href="https://www.gov.br/anvisa/pt-br/assuntos/medicamentos/cmed/precos" target="_blank" rel="noopener">CMED · princípios ativos</a>. A identificação marcada “Conferir” requer revisão da prescrição/embalagem.</footer>`;}
function render(){const root=$(state.root);if(!root)return;root.innerHTML=shell();root.onclick=click;for(const key of ['patient','control','duration','group','status'])$('hm-'+key)?.addEventListener('change',e=>{state.filters[key]=e.target.value;state.page=1;state.historyPage=1;if(key==='patient')state.historyLoaded=false;content();});$('hm-search')?.addEventListener('input',e=>{state.filters.search=e.target.value;state.page=1;state.historyPage=1;content();});for(const key of ['from','to'])$('hm-'+key)?.addEventListener('change',e=>{state[key]=e.target.value;state.historyLoaded=false;content();});content();}
function chip(m){const key=control(m);return `<span class="hm-chip hm-${esc(key)}">${esc(controlNames[key]||controlNames.revisar)}</span>`;}
function schedule(m,onlyHour=null){return hours(m).filter(h=>!onlyHour||h===onlyHour).map(h=>{const e=eventFor(m,h),done=e?.status==='executado',blocked=e&&!['executado','anulado'].includes(e.status);return `<button class="hm-dose ${done?'done':blocked?'hm-other':''}" data-action="dose" data-id="${m.id}" data-hour="${h}" title="${esc(done?`Administrado por ${e.usuario_nome||'profissional'} · ${e.registrado_em?stamp(e.registrado_em):e.horario_administrado||date(e.data)}`:blocked?'Há um registro para conferência':`Registrar ${m.nome_medicamento}, ${m.dosagem}, às ${h}`)}">${done?'✓ ':blocked?'• ':''}${h}<span>${done?'Administrado':blocked?'Conferir':'Registrar'}</span></button>`;}).join('')||'<span class="hm-muted">Horário a conferir</span>';}
const statusLabel=m=>({vigentes:'Vigente',encerrados:'Encerrada',suspensos:'Suspensa',futuros:'Início futuro'}[status(m)]);
function medRow(m,h=null){return `<tr><td class="hm-name"><strong>${esc(patientName(m))}</strong></td><td><strong>${esc(m.nome_medicamento)}</strong><small>${esc(info(m).principio_ativo||'Identificação a conferir')}</small></td><td><b>${esc(m.dosagem||'Não informada')}</b><small>${esc(m.via_administracao||'Via não informada')}</small></td><td>${chip(m)}</td><td><span class="hm-duration">${duration(m)}</span><small>${m.data_inicio?date(m.data_inicio):'Início não informado'}${m.data_fim?' → '+date(m.data_fim):''}</small></td><td class="hm-schedule">${state.tab==='daily'||state.tab==='hours'?schedule(m,h):`<span class="hm-status">${statusLabel(m)}</span><small>${esc(hours(m).join(' · '))}</small>`}</td><td class="hm-row-actions"><button data-action="detail" data-id="${m.id}">Detalhes</button>${state.gestor?`<button data-action="edit" data-id="${m.id}">Editar</button>`:''}</td></tr>`;}
function table(head,body){return `<div class="hm-table-wrap"><table><thead><tr>${head.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${body}</tbody></table></div>`;}
function pager(total,page,kind){const max=Math.max(1,Math.ceil(total/40));return `<div class="hm-pagination"><span>${total} registro(s) · página ${page} de ${max}</span><button data-action="${kind}" data-page="${page-1}" ${page<=1?'disabled':''}>Anterior</button><button data-action="${kind}" data-page="${page+1}" ${page>=max?'disabled':''}>Próxima</button></div>`;}
function content(){if(!$('hm-content'))return;const meds=filtered(),daily=state.meds.filter(m=>matches(m)&&active(m,state.day));let slots=0,done=0;daily.forEach(m=>hours(m).forEach(h=>{slots++;if(eventFor(m,h)?.status==='executado')done++;}));$('hm-stats').innerHTML=[['Pacientes',new Set(daily.map(m=>m.paciente_id)).size,''],['Prescrições vigentes',daily.length,''],['Doses registradas',`${done} / ${slots}`,'success'],['A registrar',slots-done,'warning']].map(([l,v,c])=>`<div class="${c}"><span>${l}</span><strong>${v}</strong></div>`).join('');
 if(state.tab==='history'){renderHistory();return;}
 $('hm-results').textContent=`${meds.length} prescrição(ões) · pacientes em ordem alfabética`;
 let rows=state.tab==='hours'?meds.flatMap(m=>hours(m).map(h=>({m,h}))).sort((a,b)=>compare(a.h,b.h)||orderMeds(a.m,b.m)):meds.map(m=>({m,h:null}));
 state.page=Math.min(state.page,Math.max(1,Math.ceil(rows.length/40)));
 $('hm-content').innerHTML=rows.length?table(['Paciente','Medicamento / princípio ativo','Dose / via','Controle','Tratamento',state.tab==='search'?'Situação / horários':'Administração','Ações'],rows.slice((state.page-1)*40,state.page*40).map(x=>medRow(x.m,x.h)).join(''))+pager(rows.length,state.page,'page'):'<div class="hm-empty">Nenhuma prescrição encontrada para os filtros selecionados.</div>';
}
function snapshot(e){return e.prescricao_snapshot||null;}
function historyMatches(e){const current=state.meds.find(m=>m.id===e.medicacao_id),snap=snapshot(e);return matches({...current,...snap,paciente_id:e.paciente_id,nome_paciente:e.nome_paciente});}
function historyEvents(){return state.history.filter(historyMatches).sort((a,b)=>compare(a.nome_paciente,b.nome_paciente)||compare(a.data,b.data)||compare(a.horario,b.horario));}
function rangeMeds(){return state.meds.filter(m=>matches(m)&&(!m.data_inicio||m.data_inicio<=state.to)&&(!m.data_fim||m.data_fim>=state.from)).sort(orderMeds);}
function renderHistory(){if(!state.historyLoaded){$('hm-content').innerHTML='<div class="hm-empty">Selecione o período e clique em “Consultar histórico”. Os filtros acima também se aplicam ao relatório.</div>';return;}const rows=historyEvents();state.historyPage=Math.min(state.historyPage,Math.max(1,Math.ceil(rows.length/40)));const treatments=rangeMeds();$('hm-content').innerHTML=`<div class="hm-table-heading"><b>${rows.length} registro(s) no período</b><span>${treatments.length} cadastro(s) de tratamento relacionados ao período</span></div>`+(rows.length?table(['Paciente','Data / horário previsto','Medicamento registrado','Dose registrada','Resultado','Profissional / registro','Ações'],rows.slice((state.historyPage-1)*40,state.historyPage*40).map(e=>{const snap=snapshot(e),m=state.meds.find(m=>m.id===e.medicacao_id);return `<tr><td class="hm-name"><strong>${esc(e.nome_paciente)}</strong></td><td>${date(e.data)}<small>${esc(e.horario)}</small></td><td>${esc(snap?.nome_medicamento||m?.nome_medicamento||'Cadastro indisponível')}${!snap?'<small>Vínculo atual · registro anterior à versão histórica</small>':''}</td><td>${esc(snap?.dosagem||'Sem cópia histórica da dose')}</td><td><span class="hm-chip ${e.status==='executado'?'hm-success':'hm-revisar'}">${esc(e.status==='executado'?'Administrado':e.status==='anulado'?'Anulado':e.status==='nao_obrigatorio'?'Não obrigatório':e.status)}</span></td><td>${esc(e.usuario_nome||'Não informado')}<small>${esc(e.registrado_em?stamp(e.registrado_em):e.horario_administrado||'Horário de registro não informado')}</small></td><td>${m?`<button data-action="detail" data-id="${m.id}">Prescrição</button>`:''}${m&&state.gestor&&e.status!=='anulado'?`<button data-action="void" data-id="${m.id}" data-event="${e.id}">Corrigir registro</button>`:''}</td></tr>`;}).join(''))+pager(rows.length,state.historyPage,'history-page'):'<div class="hm-empty">Não há administrações registradas nesse período. Os cadastros de tratamento continuam disponíveis no PDF.</div>');}
async function queryHistory(){if(!state.from||!state.to||state.from>state.to){notice('Informe um período válido.',true);return false;}notice('Consultando todos os registros do período…');const signature=JSON.stringify([state.from,state.to,state.filters.patient]);const records=await executions(state.from,state.to,state.filters.patient);if(signature!==JSON.stringify([state.from,state.to,state.filters.patient])){state.historyLoaded=false;notice('Os filtros mudaram. Consulte novamente para aplicar a seleção atual.');return false;}state.history=records;state.historyLoaded=true;state.historyPage=1;content();notice('Histórico atualizado.');return true;}
function modal(title,body){if(dialog&&!closeDialog())return false;lastFocus=document.activeElement;dialog=document.createElement('dialog');dialog.className='hm hm-dialog';dialog.innerHTML=`<header><h2>${esc(title)}</h2><button type="button" data-close aria-label="Fechar">×</button></header><div class="hm-dialog-body">${body}</div>`;document.body.appendChild(dialog);dialog.querySelector('[data-close]').onclick=()=>closeDialog();dialog.addEventListener('cancel',e=>{e.preventDefault();closeDialog();});dialog.showModal();return true;}
function closeDialog(force=false){if(!dialog)return true;if(!force&&state.dirty&&!confirm('Descartar alterações não salvas na prescrição?'))return false;dialog.close();dialog.remove();dialog=null;state.dirty=false;lastFocus?.focus?.();return true;}
function item(label,value){return `<div><dt>${esc(label)}</dt><dd>${esc(value||'Não informado')}</dd></div>`;}
async function detail(m){if(!modal('Detalhes da prescrição',`<p class="hm-patient-title">${esc(patientName(m))}</p><h3>${esc(m.nome_medicamento)} · ${esc(m.dosagem)}</h3>${chip(m)}<dl class="hm-details">${item('Princípio ativo',info(m).principio_ativo)}${item('Classe terapêutica',info(m).classe_terapeutica)}${item('Via',m.via_administracao)}${item('Horários',hours(m).join(' · '))}${item('Duração',duration(m))}${item('Situação',statusLabel(m))}${item('Início',date(m.data_inicio))}${item('Fim (inclusive)',m.data_fim?date(m.data_fim):'Sem término cadastrado')}${item('Prescritor',m.prescritor)}${item('Referência da receita',m.prescricao_numero)}${item('Validade cadastrada',date(m.prescricao_validade))}${item('Frequência',m.frequencia)}</dl><h4>Orientações da prescrição</h4><p class="hm-pre">${esc(m.observacoes||m.observacao||'Não informadas')}</p><p class="hm-filter-note">${esc(info(m).nota||'Confira a identificação na prescrição.')} <a href="https://consultas.anvisa.gov.br/#/bulario/" target="_blank" rel="noopener">Consultar bula oficial</a></p>${state.gestor?`<div class="hm-actions"><button id="hm-detail-edit">Editar prescrição</button><button id="hm-retro">Lançamento retroativo</button><button id="hm-suspend">${m.status_tratamento==='suspenso'?'Retomar':'Suspender'}</button><button id="hm-end" class="hm-danger">Encerrar / arquivar</button></div>`:''}<h4>Histórico de alterações</h4><div id="hm-audit">Carregando histórico…</div>`))return;
 if(state.gestor){$('hm-retro').onclick=()=>{closeDialog(true);retro(m);};$('hm-detail-edit').onclick=()=>{closeDialog(true);edit(m);};$('hm-suspend').onclick=()=>changeStatus(m,m.status_tratamento==='suspenso'?'ativo':'suspenso');$('hm-end').onclick=()=>changeStatus(m,'finalizado');}
 try{const audit=await api('audit',{id:m.id});if($('hm-audit'))$('hm-audit').innerHTML=audit.length?audit.map(a=>`<details><summary>${esc(stamp(a.created_at))} · ${esc(({prescricao_alterada:'Prescrição alterada',prescricao_incluida:'Prescrição incluída',administracao:'Administração registrada',administracao_anulada:'Administração anulada'})[a.acao]||a.acao)}</summary><p>${esc(a.motivo||'Registro do profissional responsável')}</p><dl class="hm-details">${item('Antes',auditSummary(a.antes))}${item('Depois',auditSummary(a.depois))}</dl></details>`).join(''):'Sem alterações desde a implantação do histórico.';}catch(e){if($('hm-audit'))$('hm-audit').textContent=e.message;}}
function auditSummary(x){if(!x)return '—';if(x.medicacao_id)return `${x.status} · ${date(x.data)} ${x.horario||''} · ${x.usuario_nome||''}`;return [x.nome_medicamento,x.dosagem,x.horarios,duration(x),date(x.data_inicio),x.data_fim?date(x.data_fim):'',x.status_tratamento].filter(Boolean).join(' · ');}
function edit(m=null){if(!state.gestor)return;const v=m||{data_inicio:state.day,duracao_tipo:'continuo',obrigatorio:true,paciente_id:state.filters.patient};const input=(name,type='text',extra='')=>`<input name="${name}" type="${type}" value="${esc(v[name]??'')}" ${extra}>`;const textarea=(name)=>`<textarea name="${name}" rows="3">${esc(v[name]??'')}</textarea>`;
 if(!modal(m?'Editar prescrição':'Nova prescrição',`<form id="hm-edit"><div class="hm-form-grid">${field('Paciente',`<select name="paciente_id" required ${m?'disabled':''}>${options([['','Selecione'],...state.patients.filter(p=>p.ativo!==false||p.id===v.paciente_id).map(p=>[p.id,p.nome_completo])],v.paciente_id)}</select>`)}${field('Medicamento (nome completo)',input('nome_medicamento','text','required maxlength="180" list="hm-catalog-options"'))}<datalist id="hm-catalog-options">${state.catalog.map(c=>`<option value="${esc(c.nome)}">${esc(c.principio_ativo||'Conferir identificação')}</option>`).join('')}</datalist>${field('Dose prescrita',input('dosagem','text','required maxlength="180" placeholder="Copie da prescrição, incluindo a unidade"'))}${field('Via de administração',input('via_administracao','text','maxlength="100" placeholder="Ex.: oral, subcutânea"'))}<div class="hm-full hm-message" id="hm-identification"></div>${field('Horários prescritos',input('horarios','text','required placeholder="07:00 | 13:00 | 19:00"'))}${field('Frequência / instrução',input('frequencia','text','maxlength="180" placeholder="Conforme prescrição"'))}${field('Duração',`<select name="duracao_tipo">${options([['continuo','Uso contínuo'],['temporario','Uso temporário']],v.duracao_tipo)}</select>`)}${field('Data de início',input('data_inicio','date',m?'':'required'))}${field('Dias (opcional: calcula o fim)',input('dias_tratamento','number','min="1" max="3660"'))}${field('Data final (inclui este dia)',input('data_fim','date'))}${field('Prescritor',input('prescritor','text','maxlength="180"'))}${field('Nº / referência da prescrição',input('prescricao_numero','text','maxlength="180"'))}${field('Validade da prescrição',input('prescricao_validade','date'))}${field('Obrigatoriedade',`<select name="obrigatorio">${options([['true','Obrigatório'],['false','Não obrigatório — conforme prescrição']],String(v.obrigatorio!==false))}</select>`)}<div class="hm-full">${field('Orientações e cuidados prescritos',`<textarea name="observacoes" rows="3" maxlength="4000">${esc(v.observacoes||v.observacao||'')}</textarea>`)}</div>${m?'<div class="hm-full"><label>Motivo da alteração<textarea name="motivo" required maxlength="1000" rows="2"></textarea></label></div>':''}</div><p class="hm-filter-note">Use os dados da prescrição. O tratamento temporário sai da rotina diária após a data final e permanece no histórico.</p><p id="hm-save-error" role="alert" class="hm-error"></p><div class="hm-actions"><button type="button" id="hm-edit-cancel">Cancelar</button><button class="hm-primary" type="submit">Salvar prescrição</button></div></form>`))return;
 const form=$('hm-edit'),fields=form.elements;const identify=()=>{const c=state.catalog.find(c=>c.chave===norm(fields.nome_medicamento.value));$('hm-identification').textContent=c?`${controlNames[c.lista]}${c.principio_ativo?' · '+c.principio_ativo:''}`:'Identificação a conferir. Informe o nome completo da embalagem/prescrição.';};const dates=()=>{const temporary=fields.duracao_tipo.value==='temporario';fields.data_fim.disabled=!temporary;fields.dias_tratamento.disabled=!temporary;fields.data_fim.required=temporary;fields.data_inicio.required=temporary||!m;if(!temporary){fields.data_fim.value='';fields.dias_tratamento.value='';}};const calculate=()=>{const days=Number(fields.dias_tratamento.value);if(fields.data_inicio.value&&Number.isInteger(days)&&days>0&&days<=3660){const d=new Date(fields.data_inicio.value+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+days-1);fields.data_fim.value=d.toISOString().slice(0,10);}};
 form.addEventListener('input',()=>{state.dirty=true;identify();});fields.duracao_tipo.addEventListener('change',dates);fields.dias_tratamento.addEventListener('change',calculate);fields.data_inicio.addEventListener('change',()=>{if(fields.dias_tratamento.value)calculate();});fields.data_fim.addEventListener('change',()=>{if(fields.data_inicio.value&&fields.data_fim.value)fields.dias_tratamento.value=String(Math.round((new Date(fields.data_fim.value)-new Date(fields.data_inicio.value))/86400000)+1);});$('hm-edit-cancel').onclick=()=>closeDialog();dates();identify();
 form.onsubmit=async e=>{e.preventDefault();const btn=form.querySelector('[type=submit]');btn.disabled=true;try{const data=Object.fromEntries(new FormData(form));data.id=m?.id||null;data.versao=m?.versao;data.paciente_id=m?.paciente_id||data.paciente_id;data.horarios=String(data.horarios).split(/[|,;\s]+/).filter(Boolean).map(h=>/^\d:\d\d$/.test(h)?'0'+h:h).sort().join('|');data.obrigatorio=data.obrigatorio==='true';for(const k of ['data_inicio','data_fim','prescricao_validade'])data[k]=data[k]||null;delete data.dias_tratamento;await api('save',data);state.dirty=false;closeDialog(true);state.historyLoaded=false;await load();notice('Prescrição salva.');}catch(err){$('hm-save-error').textContent=err.message;}finally{btn.disabled=false;}};
}
async function changeStatus(m,statusValue){const label=statusValue==='suspenso'?'suspender':statusValue==='ativo'?'retomar':'encerrar e arquivar';const motivo=prompt(`Informe o motivo para ${label} a prescrição de ${m.nome_medicamento} para ${patientName(m)}:`);if(!motivo?.trim())return;try{await api('status',{id:m.id,versao:m.versao,status:statusValue,motivo});closeDialog(true);state.historyLoaded=false;await load();notice('Situação atualizada. O histórico foi preservado.');}catch(e){alert(e.message);}}
async function dose(m,h){const existing=eventFor(m,h);if(existing?.status==='executado'){if(state.gestor&&confirm(`Já registrado por ${existing.usuario_nome||'profissional'}. Deseja corrigir este registro?`))await voidEvent(m,existing);return;}if(existing&&existing.status!=='anulado'){alert('Há um registro anterior nesse horário. Confira em Histórico e relatórios.');return;}
 if(!modal('Confirmar administração',`<p class="hm-patient-title">${esc(patientName(m))}</p><h3>${esc(m.nome_medicamento)}</h3><dl class="hm-details">${item('Dose',m.dosagem)}${item('Via',m.via_administracao)}${item('Horário previsto',h)}${item('Data',date(state.day))}</dl><p>Confirme somente após administrar esta medicação ao paciente.</p><p class="hm-error" id="hm-dose-error" role="alert"></p><div class="hm-actions"><button id="hm-dose-cancel">Voltar</button><button id="hm-dose-confirm" class="hm-primary">Confirmar: medicação administrada</button></div>`))return;
 $('hm-dose-cancel').onclick=()=>closeDialog(true);$('hm-dose-confirm').onclick=async()=>{const btn=$('hm-dose-confirm');btn.disabled=true;try{const e=await api('administer',{id:m.id,versao:m.versao,data:state.day,horario:h});state.execs=state.execs.filter(x=>x.id!==e.id);state.execs.push(e);closeDialog(true);state.historyLoaded=false;content();notice(`Administração registrada: ${patientName(m)} · ${m.nome_medicamento} · ${h}.`);}catch(err){if($('hm-dose-error'))$('hm-dose-error').textContent=`Não foi confirmado o registro no banco. ${err.message} Atualize antes de tentar novamente.`;}finally{btn.disabled=false;}};
}
async function voidEvent(m,e){const motivo=prompt(`Corrigir o registro de ${m.nome_medicamento} · ${patientName(m)} · ${date(e.data)} ${e.horario}. Informe o motivo (o registro original ficará no histórico):`);if(!motivo?.trim())return;try{await api('void',{id:m.id,execucao_id:e.id,motivo});await load();if(state.tab==='history')await queryHistory();notice('Registro anulado com histórico preservado.');}catch(err){notice(err.message,true);}}
async function click(event){const btn=event.target.closest('button');if(!btn||btn.disabled)return;const action=btn.dataset.action;try{if(btn.dataset.tab){state.tab=btn.dataset.tab;state.page=1;render();return;}const m=state.meds.find(m=>m.id===btn.dataset.id);if(action==='refresh')await load();if(action==='new')edit();if(action==='backup')await showBackup();if(action==='edit'&&m)edit(m);if(action==='detail'&&m)await detail(m);if(action==='dose'&&m)await dose(m,btn.dataset.hour);if(action==='void'&&m)await voidEvent(m,state.history.find(e=>e.id===btn.dataset.event));if(action==='clear'){state.filters={patient:'',search:'',control:'',duration:'',group:'',status:'vigentes'};state.page=1;state.historyLoaded=false;render();}if(action==='page'){state.page=Number(btn.dataset.page);content();}if(action==='history-page'){state.historyPage=Number(btn.dataset.page);content();}if(action==='history'){btn.disabled=true;await queryHistory();}if(action==='pdf'||action==='csv'){btn.disabled=true;await report(action);}if(action==='queue')download(JSON.stringify(queue(),null,2),'harmonia-pendencias-medicacao.json','application/json');}catch(e){notice(e.message,true);if(!token())authBox();}finally{btn.disabled=false;}}
function download(data,name,type){const blob=new Blob([data],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function csvCell(v){let s=String(v??'');if(/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}
async function report(type='pdf'){if(!state.loaded){await open();if(!state.loaded)return;}const historical=state.tab==='history';if(historical&&!await queryHistory())return;const meds=historical?rangeMeds():filtered(),events=historical?historyEvents():state.execs.filter(e=>meds.some(m=>m.id===e.medicacao_id));const title=historical?'Histórico de medicação':'Relação de tratamentos';const period=historical?`${date(state.from)} a ${date(state.to)}`:date(state.day);const headers=['Paciente','Medicamento','Dose','Via','Controle','Duração','Início','Fim','Situação','Horários'];const body=meds.map(m=>[patientName(m),m.nome_medicamento,m.dosagem,m.via_administracao||'Não informada',controlNames[control(m)],duration(m),date(m.data_inicio),m.data_fim?date(m.data_fim):'Sem término',statusLabel(m),hours(m).join(' / ')]);const eHeaders=['Paciente','Data','Horário previsto','Medicamento','Dose histórica','Resultado','Profissional','Registro'];const eBody=events.sort((a,b)=>compare(a.nome_paciente,b.nome_paciente)||compare(a.data,b.data)||compare(a.horario,b.horario)).map(e=>{const m=state.meds.find(m=>m.id===e.medicacao_id),s=snapshot(e);return [e.nome_paciente||patientName(m||{}),date(e.data),e.horario,s?.nome_medicamento||m?.nome_medicamento||'Cadastro indisponível',s?.dosagem||'Sem cópia histórica',e.status,e.usuario_nome||'',e.registrado_em?stamp(e.registrado_em):e.horario_administrado||'Não informado'];});
 if(type==='csv'){download('\uFEFF'+[[title,period],headers,...body,[],['Registros de administração'],eHeaders,...eBody].map(r=>r.map(csvCell).join(';')).join('\r\n'),'harmonia-medicacao.csv','text/csv;charset=utf-8');return;}
 if(!window.jspdf?.jsPDF)throw new Error('O gerador de PDF não carregou. Atualize a página e tente novamente.');const pdf=new window.jspdf.jsPDF({orientation:'landscape',unit:'mm',format:'a4'});if(!pdf.autoTable)throw new Error('O gerador de tabelas do PDF não carregou.');pdf.setFillColor(15,92,87);pdf.rect(0,0,297,24,'F');pdf.setTextColor(255);pdf.setFont('helvetica','bold');pdf.setFontSize(17);pdf.text('HARMONIA CARE',12,10);pdf.setFontSize(10);pdf.text(`${title} | ${period}`,12,17);pdf.setTextColor(45);pdf.setFontSize(8);const filterText=`Paciente: ${state.patients.find(p=>p.id===state.filters.patient)?.nome_completo||'Todos'} | Pesquisa: ${state.filters.search||'Todas'} | Controle: ${state.filters.control||'Todos'} | Duração: ${state.filters.duration||'Todas'} | ${historical?'Todas as situações no período':state.tab==='search'?(state.filters.status||'Todas as situações'):'Vigentes'}`;pdf.text(pdf.splitTextToSize(filterText,270),12,30);
 const styles={font:'helvetica',fontSize:7,cellPadding:2.3,overflow:'linebreak'},theme={theme:'striped',styles,headStyles:{fillColor:[15,92,87],fontStyle:'bold'},alternateRowStyles:{fillColor:[244,249,248]},margin:{left:12,right:12,bottom:17}};
 pdf.autoTable({...theme,startY:42,head:[headers],body,columnStyles:{0:{fontStyle:'bold'}}});let y=pdf.lastAutoTable.finalY+9;if(y>170){pdf.addPage();y=16;}pdf.setFontSize(10);pdf.text('Registros de administração',12,y);pdf.autoTable({...theme,startY:y+4,head:[eHeaders],body:eBody.length?eBody:[['Sem registros para esta seleção.','','','','','','','']],columnStyles:{0:{fontStyle:'bold'}}});
 for(let p=1;p<=pdf.getNumberOfPages();p++){pdf.setPage(p);pdf.setFontSize(7);pdf.setTextColor(80);pdf.text('Cadastros de tratamento: versão atual. Registros antigos sem snapshot não comprovam a dose histórica.',12,199);pdf.text(`Emitido em ${stamp(new Date().toISOString())} | Página ${p}/${pdf.getNumberOfPages()}`,12,204);}
 pdf.save(`Harmonia_Medicacao_${historical?state.from:state.day}.pdf`);notice('Relatório gerado.');
}
async function reportPatient(){if(!state.loaded){await open();return;}if(!state.filters.patient){notice('Selecione um paciente no filtro para gerar o relatório individual.',true);$('hm-patient')?.focus();return;}await report();}
async function backupApi(action,payload={}){const {data,error}=await window.db.rpc('medicacao_backup',{p_action:action,p_token:token()||null,p_payload:payload});if(error)throw new Error(error.message);return data;}
async function showBackup(){const batches=await backupApi('info');if(!modal('Backup dos registros anteriores',batches.length?batches.map((b,i)=>`<section><h3>Registros até ${date(b.cutoff)}</h3><p>Backup protegido, criado em ${esc(stamp(b.created_at))}. Os cadastros de pacientes, prescrições e modelos de rotinas também foram copiados como referência.</p><dl class="hm-details">${Object.entries(b.manifest).map(([name,m])=>item(({rotinas_execucao:'Execuções de rotinas',medicacoes_execucao:'Aplicações de medicamentos',medicacoes:'Prescrições',pacientes:'Pacientes',rotina_modelos:'Modelos de rotina'})[name]||name,Number(m.count).toLocaleString('pt-BR'))).join('')}</dl><button class="hm-primary" data-backup-index="${i}">Baixar cópia completa</button><p id="hm-backup-progress-${i}" role="status"></p></section>`).join(''):'<p>Nenhum backup arquivado disponível.</p>'))return;
 dialog.querySelectorAll('[data-backup-index]').forEach(btn=>btn.onclick=async()=>{const i=Number(btn.dataset.backupIndex),batch=batches[i],total=Object.values(batch.manifest).reduce((n,x)=>n+Number(x.count),0),records=[];btn.disabled=true;try{for(let offset=0;;offset+=500){if(!dialog)return;const page=await backupApi('export',{batch_id:batch.id,offset});records.push(...page);if($('hm-backup-progress-'+i))$('hm-backup-progress-'+i).textContent=`Preparando cópia: ${records.length.toLocaleString('pt-BR')} / ${total.toLocaleString('pt-BR')} registros…`;if(page.length<500)break;}if(records.length!==total)throw new Error('A contagem da cópia não corresponde ao manifesto. Tente novamente.');const dados={};for(const row of records)(dados[row.source]||=[]).push(row.row_data);download(JSON.stringify({sistema:'Harmonia Care',tipo:'backup-anterior-reinicio',manifesto:batch,dados}),`Harmonia_Backup_ate_${batch.cutoff}.json`,'application/json');if($('hm-backup-progress-'+i))$('hm-backup-progress-'+i).textContent='Cópia completa gerada. O original permanece guardado no banco.';}catch(e){if($('hm-backup-progress-'+i))$('hm-backup-progress-'+i).textContent=e.message;}finally{btn.disabled=false;}});
}
function retro(m){if(!state.gestor)return;if(!modal('Lançamento retroativo de administração',`<p class="hm-patient-title">${esc(patientName(m))}</p><h3>${esc(m.nome_medicamento)} · ${esc(m.dosagem)}</h3><p>Confirme a prescrição utilizada na data informada. O registro será identificado como lançamento feito agora, referente à data anterior.</p><form id="hm-retro-form"><div class="hm-form-grid">${field('Data da administração',`<input name="data" type="date" required max="${state.day}" value="${state.day}" ${m.data_inicio?'min="'+m.data_inicio+'"':''}>`)}${field('Horário previsto',`<select name="horario">${hours(m).map(h=>`<option>${h}</option>`).join('')}</select>`)}<div class="hm-full"><label>Justificativa do lançamento<textarea name="motivo" required rows="3" maxlength="1000"></textarea></label></div></div><p id="hm-retro-error" class="hm-error" role="alert"></p><button class="hm-primary" type="submit">Confirmar administração na data informada</button></form>`))return;const form=$('hm-retro-form');form.onsubmit=async e=>{e.preventDefault();const btn=form.querySelector('button');btn.disabled=true;try{const fields=Object.fromEntries(new FormData(form));await api('administer',{...fields,id:m.id,versao:m.versao,retroativo:true});closeDialog(true);state.historyLoaded=false;await load();notice('Lançamento retroativo registrado com justificativa.');}catch(err){$('hm-retro-error').textContent=err.message;}finally{btn.disabled=false;}};}
async function logout(){try{if(token())await api('logout');}catch(e){}sessionStorage.removeItem(tokenKey());state.loaded=false;}
window.HarmoniaMedicacao={open,openHours:()=>open(true),allowed,authenticate,logout,report,reportPatient,hasUnsaved:()=>state.dirty,discard:()=>closeDialog(),_test:{norm,status,active,hours,matches,csvCell,state,filtered,content,dose,report,edit}};
window.podeUsarMedicacao=allowed;window.podeEditarMedicacao=()=>state.gestor;
window.obterDataHoje=today;window.obterDataAtiva=()=>state.day;
window.carregarPacientesMedicacao=async()=>{};window.carregarStatusMedicacoes=async()=>{};
window.carregarMedicacoes=()=>open();window.carregarMedicacoesHora=()=>open(true);
document.addEventListener('DOMContentLoaded',()=>{refreshTimer=setInterval(()=>{const visible=$(state.root)?.style.display!=='none';if(state.loaded&&token()&&visible&&!dialog)load();},60000);});
window.addEventListener('beforeunload',e=>{if(state.dirty){e.preventDefault();e.returnValue='';}});
})();
