/* Painel Nutrição: cadastro, evolução, relatório e integração clínica. */
(function(){
'use strict';
const TABLE='nutricao_avaliacoes';
const state={patients:[],rows:[],editing:null,chart:null,request:0,busy:false,dirty:false,loaded:false};
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const company=()=>localStorage.getItem('empresa_id');
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const date=v=>v?String(v).slice(0,10).split('-').reverse().join('/'):'—';
const num=(v,d=1)=>v===null||v===undefined||v===''?'—':Number(v).toLocaleString('pt-BR',{maximumFractionDigits:d});
const bmi=(w,h)=>w>0&&h>0?Math.round(w/((h/100)**2)*100)/100:null;
const measures=[['peso_kg','Peso','kg',0.1,500],['altura_cm','Altura','cm',30,250],['cp_cm','Panturrilha · CP','cm',1,100],['cb_cm','Braço · CB','cm',1,100],['cc_cm','Cintura · CC','cm',1,300],['dct_mm','Dobra cutânea tricipital · DCT','mm',0.1,100],['quadril_cm','Quadril','cm',1,300],['altura_joelho_cm','Altura do joelho','cm',1,100]];
const texts=[['patologias','Patologias / condições informadas'],['estado_nutricional','Avaliação do estado nutricional'],['mastigacao_obs','Observações da mastigação / prótese'],['degluticao_obs','Observações da deglutição'],['alergias','Alergias alimentares'],['intolerancias','Intolerâncias alimentares'],['capacidade_funcional','Capacidade funcional / auxílio'],['preferencias','Preferências e recusas alimentares'],['dieta','Dieta / consistência prescrita'],['suplementacao','Suplementação prescrita'],['diurese_obs','Observações da diurese'],['orientacoes','Orientações e conduta nutricional'],['metas','Metas e plano de acompanhamento'],['observacoes','Outras observações']];
const choices=[['mastigacao','Mastigação',['Normal','Alterada']],['degluticao','Deglutição',['Normal','Alterada']],['ingestao_alimentar','Dieta e ingestão alimentar',['Aumento','Sem alteração','Diminuição']],['habito_intestinal','Hábito intestinal',['Normal','Regular','Constipado','Outro']],['diurese','Diurese',['Normal','Alterada']],['ingestao_hidrica','Ingestão hídrica',['Alta','Regular','Baixa']],['metodo_peso','Método do peso',['Aferido','Estimado','Informado']],['metodo_altura','Método da altura',['Aferida','Estimada','Informada']],['lado_cp','Lado da panturrilha',['Direito','Esquerdo']],['lado_cb','Lado do braço',['Direito','Esquerdo']]];
const checks=[['sintomas','Sintomas gastrointestinais',['Nenhum','Vômito','Anorexia / falta de apetite','Diarreia','Náusea']],['exame_fisico','Exame físico',['Sem alterações','Perda de gordura','Perda muscular','Edema','Ascite']]];
function message(text,error=false){$('ntMessage').textContent=text;$('ntMessage').dataset.error=String(error);}
function allowed(){return localStorage.getItem('usuario_perfil')==='nutricionista'||localStorage.getItem('perfil')==='nutricionista'||Number(localStorage.getItem('usuario_hierarquia'))===1;}
function token(){return sessionStorage.getItem('nutri_token_'+localStorage.getItem('usuario_id'));}
async function api(action,payload={}){const {data,error}=await window.db.rpc('nutricao_api',{p_action:action,p_token:token()||null,p_payload:payload});if(error){if((error.message||'').includes('NUTRI_AUTH')){sessionStorage.removeItem('nutri_token_'+localStorage.getItem('usuario_id'));authBox();}throw error;}if(data?.error)throw new Error(data.error);return data;}
async function authenticate(login,password){const data=await api('login',{login,senha:password});if(data.usuario_id!==localStorage.getItem('usuario_id'))throw new Error('Use a conta com a qual entrou no Harmonia Care.');sessionStorage.setItem('nutri_token_'+data.usuario_id,data.token);return data;}
function authBox(){const box=$('ntAuth');if(!box)return;box.hidden=false;$('ntAuthLogin').value=localStorage.getItem('usuario_nome')||'';}
function session(){if(!window.db||!company()||!localStorage.getItem('usuario_id')||!allowed())throw new Error('Entre no sistema para acessar a Nutrição.');}
function field(id,label,type='text',attrs=''){return `<label>${label}<input id="nt_${id}" name="${id}" type="${type}" ${attrs}></label>`;}
function select(id,label,options){return `<label>${label}<select id="nt_${id}" name="${id}"><option value="">Não informado</option>${options.map(v=>`<option>${esc(v)}</option>`).join('')}</select></label>`;}
function setup(){
const panel=$('painelNutricao');if(!panel||panel.dataset.ready)return;panel.dataset.ready='1';
panel.innerHTML=`<div class="nt-heading"><div><span class="nt-kicker">Harmonia Care · acompanhamento individual</span><h2>Nutrição</h2><span class="nt-muted">Medidas, avaliação e evolução nutricional do paciente</span></div><div class="nt-actions"><button type="button" id="ntReport">Gerar relatório PDF</button><button type="button" class="nt-primary" id="ntNew">+ Nova avaliação</button></div></div>
<form id="ntAuth" class="nt-card" hidden><h3>Confirmar acesso à Nutrição</h3><p>Use seu usuário e senha do Harmonia Care. Acesso para nutricionista e nível 1.</p><div class="nt-grid"><label>Usuário<input id="ntAuthLogin" autocomplete="username" required></label><label>Senha<input id="ntAuthPassword" type="password" autocomplete="current-password" required></label><button class="nt-primary" type="submit" id="ntAuthSubmit">Confirmar acesso</button></div></form><div class="nt-filters"><label>Paciente<select id="ntPatient"><option value="">Todos os pacientes</option></select></label><label>Período inicial<input type="date" id="ntFrom"></label><label>Período final<input type="date" id="ntTo"></label><button id="ntFilter" type="button">Atualizar</button></div><div id="ntMessage" class="nt-message" role="status" aria-live="polite"></div><div id="ntKpis" class="nt-kpis"></div>
<form id="ntForm" class="nt-card" hidden><div class="nt-heading"><h3 id="ntFormTitle">Nova avaliação</h3><button type="button" id="ntCancel">Cancelar</button></div><div class="nt-note">Cada avaliação registra uma data. IMC é um cálculo de apoio; a classificação e a conduta são preenchidas pela nutricionista.</div>
<fieldset><legend>01 · Identificação da avaliação</legend><div class="nt-grid"><label>Paciente da avaliação *<select id="nt_form_patient" required></select></label>${field('data_avaliacao','Data da avaliação *','date','required')}${field('profissional_nome','Profissional responsável *','text','required maxlength="180"')}${field('crn','CRN','text','maxlength="50"')}${field('proxima_avaliacao','Próxima avaliação','date')}</div></fieldset>
<fieldset><legend>02 · Medidas antropométricas</legend><div class="nt-grid">${measures.map(([id,label,unit,min,max])=>field(id,`${label} (${unit})`,'number',`step="0.01" min="${min}" max="${max}" inputmode="decimal"`)).join('')}<label>IMC (kg/m²)<input id="nt_imc" readonly aria-live="polite" placeholder="Peso ÷ altura²"></label>${choices.filter(x=>['metodo_peso','metodo_altura','lado_cp','lado_cb'].includes(x[0])).map(x=>select(...x)).join('')}</div><p class="nt-muted">Altura em centímetros. Registre o método e o lado para comparar medidas equivalentes. DCT: dobra cutânea tricipital; CC: cintura.</p><div id="ntExtras"></div><button type="button" id="ntAddMeasure">+ Outra medida sugerida pela nutricionista</button></fieldset>
<fieldset><legend>03 · Avaliação alimentar e clínica</legend><div class="nt-grid">${choices.filter(x=>!['metodo_peso','metodo_altura','lado_cp','lado_cb'].includes(x[0])).map(x=>select(...x)).join('')}${field('agua_ml','Água ingerida (mL/dia)','number','min="0" max="15000" step="1"')}${texts.filter(x=>!['orientacoes','metas','observacoes'].includes(x[0])).map(([id,label])=>`<label class="nt-span">${label}<textarea id="nt_${id}" name="${id}" maxlength="5000"></textarea></label>`).join('')}${checks.map(([id,label,opts])=>`<div class="nt-full"><p><b>${label}</b></p><div class="nt-checks">${opts.map(v=>`<label><input type="checkbox" name="${id}" value="${esc(v)}">${esc(v)}</label>`).join('')}</div></div>`).join('')}</div></fieldset>
<fieldset><legend>04 · Conduta e acompanhamento</legend><div class="nt-grid">${texts.filter(x=>['orientacoes','metas','observacoes'].includes(x[0])).map(([id,label])=>`<label class="nt-full">${label}<textarea id="nt_${id}" name="${id}" maxlength="10000"></textarea></label>`).join('')}</div></fieldset><div class="nt-actions"><button type="submit" class="nt-primary" id="ntSave">Salvar avaliação</button><span class="nt-muted">Campos sem medida podem ficar em branco.</span></div></form>
<div class="nt-card" id="ntChartCard" hidden><div class="nt-heading"><h3>Evolução das medidas</h3><label>Indicador<select id="ntMetric">${[['peso_kg','Peso (kg)'],['imc','IMC (kg/m²)'],...measures.filter(x=>x[0]!=='peso_kg').map(x=>[x[0],`${x[1]} (${x[2]})`])].map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></label></div><div class="nt-chart"><canvas id="ntChart" aria-label="Evolução nutricional por data" role="img"></canvas></div><p id="ntChartNote" class="nt-muted"></p></div>
<div class="nt-card"><div class="nt-heading"><h3>Histórico de avaliações</h3><span class="nt-muted">Medidas e observações por consulta</span></div><div id="ntHistory" class="nt-table"></div></div>`;
$('ntAuth').onsubmit=async e=>{e.preventDefault();$('ntAuthSubmit').disabled=true;try{await authenticate($('ntAuthLogin').value,$('ntAuthPassword').value);$('ntAuthPassword').value='';$('ntAuth').hidden=true;await open(window.HarmoniaNutricao.target);window.HarmoniaNutricao.target=null;summary($('buscaPaciente')?.value);}catch(err){message(err.message,true);}finally{$('ntAuthSubmit').disabled=false;}};
$('ntNew').onclick=()=>{if(!token()){authBox();message('Confirme seu acesso antes de cadastrar.',true);return;}edit(null);};$('ntCancel').onclick=()=>cancel();$('ntForm').onsubmit=save;$('ntFilter').onclick=()=>refresh();$('ntReport').onclick=report;$('ntMetric').onchange=chart;$('ntAddMeasure').onclick=()=>{extra();state.dirty=true;};
$('ntPatient').onchange=async()=>{if(state.dirty&&!confirm('Descartar alterações não salvas?')){$('ntPatient').value=state.filterPatient||'';return;}closeForm();state.filterPatient=$('ntPatient').value;await refresh();};
$('ntForm').addEventListener('input',()=>{state.dirty=true;$('nt_imc').value=num(bmi(Number($('nt_peso_kg').value),Number($('nt_altura_cm').value)),2);});
$('ntForm').addEventListener('change',e=>{state.dirty=true;if(['sintomas','exame_fisico'].includes(e.target.name)&&e.target.checked){const none=checks.find(x=>x[0]===e.target.name)[2][0];document.querySelectorAll(`#ntForm input[name="${e.target.name}"]`).forEach(el=>{if(el!==e.target&&(e.target.value===none||el.value===none))el.checked=false;});}});
panel.addEventListener('click',e=>{const b=e.target.closest('[data-nt-action]');if(!b)return;const row=state.rows.find(x=>x.id===b.dataset.id);if(!row)return;if(b.dataset.ntAction==='edit')edit(row);if(b.dataset.ntAction==='delete')remove(row);});
window.addEventListener('beforeunload',e=>{if(state.dirty){e.preventDefault();e.returnValue='';}});
}
async function patients(){
session();state.patients=await api('patients');
const old=$('ntPatient').value;const opts=state.patients.map(p=>`<option value="${esc(p.id)}">${esc(p.nome_completo||p.nome_apelido)}${p.ativo===false?' (inativo)':''}</option>`).join('');$('ntPatient').innerHTML='<option value="">Todos os pacientes</option>'+opts;$('nt_form_patient').innerHTML='<option value="">Selecione o paciente</option>'+opts;$('ntPatient').value=old;
}
async function open(patientId){setup();try{session();if(!token()){authBox();message('Confirme o acesso para carregar os dados nutricionais.');return;}await patients();if(patientId){$('ntPatient').value=patientId;state.filterPatient=patientId;}window.HarmoniaNutricao.target=null;await refresh();}catch(e){message('Não foi possível carregar: '+e.message,true);}}
async function readRows(patientId,from,to){
return await api('list',{paciente_id:patientId||null,from:from||null,to:to||null});
}
async function refresh(){
const request=++state.request;state.loaded=false;message('Carregando avaliações…');$('ntReport').disabled=true;
try{session();const from=$('ntFrom').value,to=$('ntTo').value;if(from&&to&&from>to)throw new Error('O início do período deve ser anterior ao fim.');const rows=await readRows($('ntPatient').value,from,to);if(request!==state.request)return;state.rows=rows;state.loaded=true;render();message(`${rows.length} avaliação(ões) no período selecionado.`);$('ntReport').disabled=false;}catch(e){if(request!==state.request)return;state.rows=[];render();message('Falha ao consultar: '+e.message,true);}}
function patientName(id){const p=state.patients.find(p=>p.id===id);return p?.nome_completo||p?.nome_apelido||'Paciente';}
function render(){
const rows=state.rows;const selected=$('ntPatient').value;const last=rows[0];const weights=selected?rows.filter(r=>r.peso_kg!=null):[];const weight=weights[0],previous=weights[1],imcRow=rows.find(r=>r.imc!=null);const delta=weight&&previous?Number(weight.peso_kg)-Number(previous.peso_kg):null;
const latest=new Map();rows.forEach(r=>{if(!latest.has(r.paciente_id))latest.set(r.paciente_id,r);});
const due=[...latest.values()].filter(r=>r.proxima_avaliacao&&r.proxima_avaliacao<=today()).length;
const cards=selected?[['Último peso',`${num(weight?.peso_kg)} kg`,date(weight?.data_avaliacao)],['Último IMC',num(imcRow?.imc,2),`kg/m² · ${date(imcRow?.data_avaliacao)}`],['Variação de peso',delta===null?'—':`${delta>0?'+':''}${num(delta)} kg`,previous?`${num(delta/Number(previous.peso_kg)*100)}% desde ${date(previous.data_avaliacao)}`:'Sem medida anterior'],['Próxima avaliação',date(last?.proxima_avaliacao),last?.proxima_avaliacao&&last.proxima_avaliacao<=today()?'Reavaliação prevista até hoje':'Data definida pela nutricionista']]:[['Avaliações',rows.length,'No período selecionado'],['Pacientes avaliados',latest.size,'Com registro no período'],['Sem avaliação no período',state.patients.filter(p=>p.ativo!==false&&!latest.has(p.id)).length,'Pacientes ativos'],['Reavaliações previstas',due,'Até hoje · últimas consultas do período']];
$('ntKpis').innerHTML=cards.map(([title,value,note])=>`<div class="nt-kpi"><span>${esc(title)}</span><strong>${esc(value)}</strong><small class="nt-muted">${esc(note)}</small></div>`).join('');
$('ntHistory').innerHTML=rows.length?`<table><thead><tr><th>Data / paciente</th><th>Peso kg</th><th>Altura cm</th><th>IMC</th><th>CP cm</th><th>CB cm</th><th>Avaliação / profissional</th><th>Ações</th></tr></thead><tbody>${rows.map(r=>`<tr><td><b>${date(r.data_avaliacao)}</b><br>${esc(patientName(r.paciente_id))}</td><td>${num(r.peso_kg)}</td><td>${num(r.altura_cm)}</td><td>${num(r.imc,2)}</td><td>${num(r.cp_cm)}</td><td>${num(r.cb_cm)}</td><td>${esc(r.ficha?.estado_nutricional||'Não informado')}<br><small class="nt-muted">${esc(r.profissional_nome)}</small></td><td><button type="button" data-nt-action="edit" data-id="${r.id}">Abrir / editar</button> <button type="button" class="nt-danger" data-nt-action="delete" data-id="${r.id}">Excluir</button></td></tr>`).join('')}</tbody></table>`:'<div class="nt-empty">Nenhuma avaliação neste período. Selecione um paciente e clique em <b>Nova avaliação</b>.</div>';
chart();
}
function chart(){
if(state.chart){state.chart.destroy();state.chart=null;}const selected=$('ntPatient').value;$('ntChartCard').hidden=!selected;if(!selected)return;
const key=$('ntMetric').value;const rows=[...state.rows].reverse().filter(r=>r[key]!==null&&r[key]!==undefined);$('ntChartNote').textContent=rows.length?`${rows.length} medida(s) registrada(s). Valores ausentes não são tratados como zero. Compare o método de aferição nas avaliações.`:'Sem medidas deste indicador no período.';
if(!window.Chart){$('ntChartNote').textContent+=' Gráfico indisponível; consulte os valores na tabela.';return;}state.chart=new Chart($('ntChart'),{type:'line',data:{labels:rows.map(r=>date(r.data_avaliacao)),datasets:[{label:$('ntMetric').selectedOptions[0].textContent,data:rows.map(r=>Number(r[key])),borderColor:'#087f78',backgroundColor:'rgba(8,127,120,.10)',fill:true,tension:.15,pointRadius:5,pointBackgroundColor:'#087f78'}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:false},x:{grid:{display:false}}}}});
}
function extra(data={}){const div=document.createElement('div');div.className='nt-extra';div.innerHTML=`<label>Nome da medida<input data-extra="nome" required maxlength="100" value="${esc(data.nome)}"></label><label>Valor<input data-extra="valor" type="number" step="any" min="0" required value="${esc(data.valor)}"></label><label>Unidade<input data-extra="unidade" required maxlength="30" placeholder="cm, mm…" value="${esc(data.unidade)}"></label><button type="button" class="nt-danger">Remover medida</button>`;div.querySelector('button').onclick=()=>{div.remove();state.dirty=true;};$('ntExtras').appendChild(div);}
function closeForm(){state.editing=null;state.dirty=false;$('ntForm').hidden=true;}
function cancel(){if(state.dirty&&!confirm('Descartar alterações não salvas?'))return;closeForm();}
function edit(row){
if(state.busy)return;if(state.dirty&&!confirm('Descartar alterações não salvas?'))return;state.editing=row;$('ntForm').reset();$('ntExtras').innerHTML='';$('ntForm').hidden=false;$('ntFormTitle').textContent=row?'Editar avaliação de '+date(row.data_avaliacao):'Nova avaliação';
$('nt_form_patient').value=row?.paciente_id||$('ntPatient').value;$('nt_form_patient').disabled=!!row;$('nt_data_avaliacao').value=row?.data_avaliacao||today();$('nt_data_avaliacao').max=today();$('nt_profissional_nome').value=row?.profissional_nome||localStorage.getItem('usuario_nome')||'';$('nt_crn').value=row?.crn||'';$('nt_proxima_avaliacao').value=row?.proxima_avaliacao||'';
measures.forEach(([id])=>$('nt_'+id).value=row?.[id]??'');$('nt_imc').value=num(row?.imc,2);[...texts,...choices,['agua_ml']].forEach(([id])=>$('nt_'+id).value=row?.ficha?.[id]??'');checks.forEach(([id])=>document.querySelectorAll(`#ntForm input[name="${id}"]`).forEach(el=>el.checked=(row?.ficha?.[id]||[]).includes(el.value)));(row?.medidas_extras||[]).forEach(extra);state.dirty=false;$('ntForm').scrollIntoView({behavior:'smooth',block:'start'});
}
async function save(event){
event.preventDefault();if(state.busy||!$('ntForm').reportValidity())return;
try{session();const p=state.patients.find(p=>p.id===$('nt_form_patient').value);if(!p)throw new Error('Selecione um paciente.');const day=$('nt_data_avaliacao').value,next=$('nt_proxima_avaliacao').value;if(day>today())throw new Error('A avaliação não pode ter data futura.');if(next&&next<day)throw new Error('A próxima avaliação deve ser igual ou posterior à consulta.');
const ficha={};[...texts,...choices].forEach(([id])=>ficha[id]=$('nt_'+id).value.trim()||null);ficha.agua_ml=$('nt_agua_ml').value===''?null:Number($('nt_agua_ml').value);checks.forEach(([id])=>ficha[id]=[...document.querySelectorAll(`#ntForm input[name="${id}"]:checked`)].map(el=>el.value));
const payload={empresa_id:company(),paciente_id:p.id,data_avaliacao:day,proxima_avaliacao:next||null,profissional_nome:$('nt_profissional_nome').value.trim(),crn:$('nt_crn').value.trim()||null,ficha,medidas_extras:[...$('ntExtras').children].map(el=>({nome:el.querySelector('[data-extra="nome"]').value.trim(),valor:Number(el.querySelector('[data-extra="valor"]').value),unidade:el.querySelector('[data-extra="unidade"]').value.trim()})),atualizado_por:localStorage.getItem('usuario_id')};
if(!payload.profissional_nome)throw new Error('Informe a profissional responsável.');measures.forEach(([id,label,unit,min,max])=>{const val=$('nt_'+id).value;payload[id]=val===''?null:Number(val);if(val!==''&&(!Number.isFinite(payload[id])||payload[id]<min||payload[id]>max))throw new Error(`Confira ${label} em ${unit}.`);});
if(!payload.peso_kg&&!payload.altura_cm&&!payload.cp_cm&&!payload.cb_cm&&!payload.cc_cm&&!payload.dct_mm&&!payload.quadril_cm&&!payload.altura_joelho_cm&&!payload.medidas_extras.length&&!Object.values(ficha).some(v=>Array.isArray(v)?v.length:v!==null&&v!==''))throw new Error('Registre pelo menos uma medida ou informação da avaliação.');
state.busy=true;$('ntSave').disabled=true;message('Salvando avaliação…');if(state.editing){payload.id=state.editing.id;payload.versao=state.editing.versao;}await api('save',payload);
closeForm();$('ntPatient').value=p.id;state.filterPatient=p.id;await refresh();message('Avaliação salva e vinculada à evolução do paciente.');window.dispatchEvent(new CustomEvent('nutricao:updated',{detail:{pacienteId:p.id}}));
}catch(e){message('Não foi possível salvar: '+e.message,true);}finally{state.busy=false;$('ntSave').disabled=false;}}
async function remove(row){
if(state.busy)return;const reason=prompt(`Excluir a avaliação de ${patientName(row.paciente_id)}, de ${date(row.data_avaliacao)}?\nInforme o motivo. O registro ficará preservado para rastreabilidade.`);if(reason===null)return;if(!reason.trim()){message('Informe o motivo da exclusão.',true);return;}
try{session();state.busy=true;await api('delete',{id:row.id,versao:row.versao,motivo:reason.trim()});if(state.editing?.id===row.id)closeForm();await refresh();message('Avaliação excluída do acompanhamento, com histórico preservado.');window.dispatchEvent(new CustomEvent('nutricao:updated',{detail:{pacienteId:row.paciente_id}}));}catch(e){message('Não foi possível excluir: '+e.message,true);}finally{state.busy=false;}}
function report(){
try{if(!state.loaded)throw new Error('Atualize os dados antes de gerar o relatório.');if(!state.rows.length)throw new Error('Não há avaliações no período.');if(!window.jspdf?.jsPDF)throw new Error('A biblioteca PDF não carregou. Recarregue a página.');const doc=new window.jspdf.jsPDF();const rows=state.rows;const patient=$('ntPatient').value;const period=`${date($('ntFrom').value)} a ${date($('ntTo').value)}`;const title='Harmonia Care | Nutrição';
const header=()=>{doc.setFontSize(18);doc.setTextColor(8,127,120);doc.text(title,14,18);doc.setFontSize(10);doc.setTextColor(50);doc.text(patient?patientName(patient):'Acompanhamento nutricional geral',14,26);doc.text(`Período: ${period} | Emitido em ${new Date().toLocaleString('pt-BR')}`,14,32);};header();
doc.autoTable({startY:39,head:[['Data','Paciente','Peso kg','Altura cm','IMC','CP cm','CB cm']],body:rows.map(r=>[date(r.data_avaliacao),patientName(r.paciente_id),num(r.peso_kg),num(r.altura_cm),num(r.imc,2),num(r.cp_cm),num(r.cb_cm)]),styles:{fontSize:8,cellPadding:3},headStyles:{fillColor:[8,127,120]},margin:{top:16,bottom:18}});
for(const r of rows){doc.addPage();header();const details=[['Data da avaliação',date(r.data_avaliacao)],['Paciente',patientName(r.paciente_id)],['Responsável / CRN',`${r.profissional_nome} / ${r.crn||'Não informado'}`],['Próxima avaliação',date(r.proxima_avaliacao)],...measures.map(([id,label,unit])=>[`${label} (${unit})`,num(r[id])]),['IMC (kg/m²)',num(r.imc,2)],...(r.medidas_extras||[]).map(m=>[`${m.nome} (${m.unidade})`,num(m.valor,2)]),...choices.map(([id,label])=>[label,r.ficha?.[id]||'Não informado']),...texts.map(([id,label])=>[label,r.ficha?.[id]||'Não informado']),...checks.map(([id,label])=>[label,(r.ficha?.[id]||[]).join(', ')||'Não informado']),['Água (mL/dia)',num(r.ficha?.agua_ml,0)]];
doc.autoTable({startY:39,head:[['Avaliação nutricional',date(r.data_avaliacao)]],body:details,styles:{fontSize:9,cellPadding:3,overflow:'linebreak'},columnStyles:{0:{cellWidth:60}},headStyles:{fillColor:[8,127,120]},margin:{top:16,bottom:20}});}
const total=doc.getNumberOfPages();for(let i=1;i<=total;i++){doc.setPage(i);doc.setFontSize(8);doc.setTextColor(90);doc.text('Documento assistencial confidencial · Avaliação e conduta da profissional responsável.',14,286);doc.text(`${i}/${total}`,190,286,{align:'right'});}doc.save(`harmonia-nutricao-${patient?'paciente':'geral'}-${today()}.pdf`);message('Relatório PDF gerado com as avaliações do período.');}catch(e){message(e.message,true);}}
async function summary(patientId){
const host=$('nutricaoEvolucaoPaciente');if(!host)return;host.dataset.patient=patientId||'';host.innerHTML='';if(!patientId||patientId==='todos'||!company())return;
if(!allowed())return;if(!token()){host.innerHTML='<div class="nt-summary"><h3>Evolução nutricional</h3><p>Confirme o acesso no painel Nutrição para consultar as avaliações.</p><button type="button">Abrir Nutrição</button></div>';host.querySelector('button').onclick=()=>{window.HarmoniaNutricao.target=patientId;window.abrirPainel('painelNutricao');};return;}
try{const data=await api('list',{paciente_id:patientId});if(host.dataset.patient!==patientId)return;const r=data?.[0];host.innerHTML=`<div class="nt-summary"><h3>Evolução nutricional</h3>${r?`<p>Última avaliação: <b>${date(r.data_avaliacao)}</b> · ${esc(r.profissional_nome)}</p><div class="nt-summary-values"><span>Peso <b>${num(r.peso_kg)} kg</b></span><span>IMC <b>${num(r.imc,2)}</b></span><span>CP <b>${num(r.cp_cm)} cm</b></span><span>CB <b>${num(r.cb_cm)} cm</b></span></div><p>${esc(r.ficha?.estado_nutricional||'Estado nutricional não informado')}</p><p>${esc(r.ficha?.orientacoes||'')}</p><small>Próxima avaliação: ${date(r.proxima_avaliacao)}</small>`:'<p>Paciente ainda sem avaliação nutricional.</p>'}<br><button type="button">Abrir acompanhamento de Nutrição</button></div>`;host.querySelector('button').onclick=()=>{window.HarmoniaNutricao.target=patientId;window.abrirPainel('painelNutricao');};}catch(e){host.textContent='Não foi possível consultar a evolução nutricional: '+e.message;}}
window.HarmoniaNutricao={open,summary,allowed,authenticate,api,target:null,hasUnsaved:()=>state.dirty,discard:closeForm,bmi};
window.addEventListener('nutricao:updated',()=>summary($('buscaPaciente')?.value));
function initialize(){setup();const originalLogin=window.login;if(typeof originalLogin==='function')window.login=async function(){const login=$('usuario')?.value,password=$('senha')?.value;await originalLogin.apply(this,arguments);if(allowed()&&localStorage.getItem('usuario_id')&&$('app')?.style.display!=='none'){try{await authenticate(login,password);}catch(e){console.warn('Nutrição: confirme o acesso ao abrir o painel.');}}if($('btnEquipe'))$('btnEquipe').style.display=window.HarmoniaEquipe?.allowed()?'inline-block':'none';const button=$('btnNutricao');if(button)button.style.display=allowed()?'inline-block':'none';};const originalLogout=window.logout;window.logout=async function(){try{if(token())await api('logout');}catch(e){}sessionStorage.removeItem('nutri_token_'+localStorage.getItem('usuario_id'));if(originalLogout)originalLogout();};if($('btnNutricao'))$('btnNutricao').style.display=allowed()?'inline-block':'none';if($('btnEquipe'))$('btnEquipe').style.display=window.HarmoniaEquipe?.allowed()?'inline-block':'none';}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initialize,{once:true});else initialize();
})();
