// Synthetic fixtures only. NODE_PATH may point to the QA dependencies directory.
const {JSDOM}=require('jsdom'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {jsPDF}=require('jspdf');require('jspdf-autotable');
(async()=>{
const dom=new JSDOM('<section id="painelMedicacao"></section><section id="painelMedicacaoHora" style="display:none"></section>',{url:'https://example.test/',runScripts:'outside-only'}),w=dom.window,d=w.document,$=id=>d.getElementById(id);
w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};w.confirm=()=>true;w.alert=()=>{};w.prompt=()=> 'Correção fictícia';w.jspdf={jsPDF};let pdfs=0;jsPDF.API.save=function(){assert(this.output('arraybuffer').byteLength>1500);pdfs++;};
Object.entries({usuario_id:'u1',usuario_hierarquia:'1',usuario_perfil:'administrador'}).forEach(([k,v])=>w.localStorage.setItem(k,v));w.sessionStorage.setItem('med_token_u1','synthetic');
const patient=[{id:'p1',nome_completo:'Zélia Fictícia',ativo:true},{id:'p2',nome_completo:'Ágata Fictícia',ativo:true}],day='2026-09-17',base={ativo:true,status_tratamento:'ativo',duracao_tipo:'continuo',horarios:'07:00|19:00',dosagem:'DOSE FICTÍCIA',data_inicio:'2026-01-01',data_fim:null,versao:1,paciente_ativo:true,classificacao_info:{lista:'C1',principio_ativo:'QUETIAPINA',classe_terapeutica:'Antipsicótico'}};
let meds=[{...base,id:'m1',paciente_id:'p1',nome_paciente:patient[0].nome_completo,nome_medicamento:'QUETIAPINA'},{...base,id:'m2',paciente_id:'p2',nome_paciente:patient[1].nome_completo,nome_medicamento:'QUETIAPINA'},{...base,id:'m3',paciente_id:'p2',nome_paciente:patient[1].nome_completo,nome_medicamento:'Temporário fictício',duracao_tipo:'temporario',data_fim:'2026-09-16'},{...base,id:'m4',paciente_id:'p1',nome_paciente:patient[0].nome_completo,nome_medicamento:'<img src=x onerror=alert(1)>',classificacao_info:{lista:'revisar'}}],events=[],failAdmin=false,adminCalls=[],saved=null;
w.db={rpc:async(_,{p_action:a,p_payload:p})=>{if(a==='workspace')return{data:{usuario_id:'u1',hoje:day,patients:patient,prescriptions:meds,catalog:[],gestor:true}};if(a==='executions')return{data:events.slice(p.offset,p.offset+500)};if(a==='administer'){adminCalls.push(p);if(failAdmin)return{error:{message:'Falha de rede simulada'}};const e={id:'e1',medicacao_id:p.id,paciente_id:meds.find(m=>m.id===p.id).paciente_id,data:p.data,horario:p.horario,status:'executado',usuario_nome:'Profissional fictício',prescricao_snapshot:{...meds.find(m=>m.id===p.id)}};events=[e];return{data:e};}if(a==='save'){saved=p;return{data:{...p,versao:2}};}if(a==='audit')return{data:[]};throw Error(a);}};
w.eval(fs.readFileSync(path.join(__dirname,'../js/medicacao-v2.js'),'utf8'));const api=w.HarmoniaMedicacao,t=api._test;await api.open();
assert.equal(t.active(meds[2],day),false);assert.equal(t.active(meds[2],'2026-09-16'),true);assert.equal(t.active({...base,data_inicio:'2026-09-18'},day),false);assert.equal(t.active({...base,status_tratamento:'suspenso'},day),false);
assert.equal(d.querySelector('.hm-name strong').textContent,'Ágata Fictícia');assert(!d.querySelector('img'));assert.equal(t.filtered().length,3);
$('hm-control').value='controlados';$('hm-control').dispatchEvent(new w.Event('change'));assert.equal(t.filtered().length,2);
await t.dose(meds[1],'07:00');failAdmin=true;await $('hm-dose-confirm').onclick();assert.equal(d.querySelectorAll('.hm-dose.done').length,0);assert($('hm-dose-error').textContent.includes('Não foi confirmado'));failAdmin=false;await $('hm-dose-confirm').onclick();assert.equal(d.querySelectorAll('.hm-dose.done').length,1);assert.equal(adminCalls.at(-1).id,'m2');assert.equal(events.length,1);
await api.report();assert.equal(pdfs,1);
t.edit(meds[0]);const form=$('hm-edit');form.elements.duracao_tipo.value='temporario';form.elements.duracao_tipo.dispatchEvent(new w.Event('change'));form.elements.data_inicio.value='2026-09-17';form.elements.dias_tratamento.value='7';form.elements.dias_tratamento.dispatchEvent(new w.Event('change'));assert.equal(form.elements.data_fim.value,'2026-09-23');form.elements.motivo.value='Teste';await form.onsubmit({preventDefault(){}});assert.equal(saved.data_fim,'2026-09-23');assert.equal(saved.paciente_id,'p1');assert.equal(saved.versao,1);
t.state.tab='history';t.state.filters.control='';t.state.from='2026-01-01';t.state.to=day;await api.open();await api.report();assert.equal(pdfs,2);assert.equal(t.state.historyLoaded,true);
await api.openHours();assert.equal(t.state.tab,'hours');assert.equal(d.querySelectorAll('#painelMedicacaoHora .hm-dose').length,6);
assert.equal(t.csvCell('=SUM(A1)'),"\"'=SUM(A1)\"");w.localStorage.setItem('usuario_hierarquia','4');w.localStorage.setItem('usuario_perfil','cuidador');assert.equal(api.allowed(),false);
console.log('PASS: alphabetic order, escaping, controlled filters, inclusive expiry, schedule isolation, no false confirmation on error, form dates, patient binding, historical PDF and hourly view.');w.close();
})().catch(e=>{console.error(e);process.exitCode=1;});
