// Testes de interface com dados fictícios. Dependências: jsdom 26.1.0, jspdf 2.5.1, jspdf-autotable 3.8.2.
const {JSDOM}=require('jsdom'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {jsPDF}=require('jspdf');require('jspdf-autotable');const root=path.resolve(__dirname,'..');
(async()=>{
const dom=new JSDOM('<div id="app"><button id="btnNutricao"></button><button id="btnEquipe"></button><section id="painelNutricao"></section><section id="painelEquipe"></section><div id="nutricaoEvolucaoPaciente"></div></div>',{url:'https://example.test/',runScripts:'outside-only'});const w=dom.window,d=w.document,$=id=>d.getElementById(id);w.HTMLElement.prototype.scrollIntoView=function(){};w.confirm=()=>true;w.prompt=()=> 'Teste de exclusão';w.Chart=class{destroy(){}};w.jspdf={jsPDF};let pdfs=0;jsPDF.API.save=function(){assert(this.output('arraybuffer').byteLength>1000);pdfs++;};
const uid='11111111-1111-4111-8111-111111111111',pid='22222222-2222-4222-8222-222222222222',cid='33333333-3333-4333-8333-333333333333';Object.entries({usuario_id:uid,empresa_id:'empresa',usuario_nome:'Teste profissional',usuario_perfil:'nutricionista',usuario_hierarquia:'1'}).forEach(([k,v])=>w.localStorage.setItem(k,v));w.sessionStorage.setItem('nutri_token_'+uid,'test');
const patients=[{id:pid,nome_completo:'Paciente fictício',ativo:true}],users=[{id:cid,nome_completo:'Cuidador fictício',nome_apelido:'teste',email:'teste@example.invalid',ativo:true,signature:'test'}];let rows=[],links=[];
w.db={rpc:async(name,{p_action:a,p_payload:p})=>{let data;if(a==='patients')data=patients;else if(a==='list')data=rows;else if(a==='save'){let r=rows.find(r=>r.id===p.id);if(r)Object.assign(r,p,{versao:r.versao+1});else{r={...p,id:'registro-teste',versao:1};rows.unshift(r);}r.imc=Math.round(r.peso_kg/(r.altura_cm/100)**2*100)/100;data={id:r.id};}else if(a==='delete'){rows=[];data={ok:true};}else if(a==='team_list')data={users,patients,links};else if(a==='team_save'){Object.assign(users[0],p);links=p.links.map(v=>({...v,usuario_id:cid}));data={ok:true};}return {data,error:null};}};
for(const f of ['nutricao.js','equipe.js'])w.eval(fs.readFileSync(path.join(root,'js',f),'utf8'));d.dispatchEvent(new w.Event('DOMContentLoaded'));await w.HarmoniaNutricao.open(pid);$('ntNew').click();const fill=(id,v)=>{$(id).value=v;$(id).dispatchEvent(new w.Event('input',{bubbles:true}));};fill('nt_peso_kg','64');fill('nt_altura_cm','160');fill('nt_cp_cm','32');fill('nt_cb_cm','28');fill('nt_orientacoes','Orientação fictícia');assert.equal($('nt_imc').value,'25');$('ntAddMeasure').click();d.querySelector('[data-extra=nome]').value='Medida adicional';d.querySelector('[data-extra=valor]').value='20';d.querySelector('[data-extra=unidade]').value='cm';await $('ntForm').onsubmit({preventDefault(){}});assert.equal(rows.length,1);assert.equal(rows[0].medidas_extras[0].valor,20);assert.equal(rows[0].imc,25);d.querySelector('[data-nt-action=edit]').click();fill('nt_peso_kg','65');await $('ntForm').onsubmit({preventDefault(){}});assert.equal(rows[0].peso_kg,65);$('ntReport').click();assert.equal(pdfs,1);await w.HarmoniaNutricao.summary(pid);assert($('nutricaoEvolucaoPaciente').textContent.includes('65'));
d.querySelector('[data-nt-action=delete]').click();await new Promise(r=>setTimeout(r,20));assert.equal(rows.length,0);await w.HarmoniaEquipe.open();d.querySelector('[data-eq-user]').click();d.querySelector('#eqPatients input[data-turn=manha]').checked=true;await $('eqEditor').onsubmit({preventDefault(){}});assert.equal(links.length,1);$('eqPDF').click();assert.equal(pdfs,2);w.localStorage.setItem('usuario_hierarquia','5');w.localStorage.setItem('usuario_perfil','cuidador');assert.equal(w.HarmoniaNutricao.allowed(),false);assert.equal(w.HarmoniaEquipe.allowed(),false);console.log('PASS: criar, editar, excluir, IMC, medidas adicionais, evolução, dois PDFs, vínculos e visibilidade por perfil.');dom.window.close();
})().catch(e=>{console.error(e);process.exitCode=1;});
